# GIT: ES UN SISTEMA DE CONTROL DE VERSIONES GRATUITO Y DE CODIGO ABIERTO. 
# ES UN SISTEMA QUE NOS PERMITE TENER DIFERENTES VERSIONES DE NUESTRO PROYECTO, Y SI COMETEMOS UN ERROR EN ALGUN PUNTO, PODEMOS VOLVER A ESA INSTANCIA PARA
# ARREGLARLO. 
# TIENE TRES ESTADOS: 
# * WORKING AREA: AREA DONDE SE ESTA TRABAJANDO, ESCRIBIENDO EL CODIGO. PREPARAMOS LAS CAJAS 
# * STAGE AREA: SE AGREGAN LAS CAJAS LISTAS
# * REPOSITORY: YA ES EL LOTE LISTO

# REPOSITORIO: ES UN ESAPCIO CENTRALIZADO DONDDE SE ALMACENA, ORGANIZA, Y SE MNATIENE Y DIFUNDE INFO, ES LA CARPETA QUE CONTIENE NUESTRO PROYECTO PARA COMPARTIRLO 4
# CON NUESTRO EQUIPO, PARA DESPUES ALMACENARLO EN LA NUBE. 

# PARA CREAR UN REPOSITORIO, HAY QUE SEGUIR LOS SIGUIENTES PASOS: 
# * GIT INIT: CREA REPOSITORIO DE FORMA LOCAL, EN LA CARPETA POSICIONADA. Y TAMBIEN EN ALGUNA CARPETA DONDE NO ESTEMOS POSICIONADOS, PASANDOLE LA DIRECCION
# * GIT STATUS: ESTADO DEL REPOSITORIO, SI HAY ALGUN ARCHIVO EN EL REPOSITORIO PARA AGREGAR, BORRAR, O MODIFICAR.
# * GIT ADD: SIRVE PARA PASAR DEL ESTADO DE WORKING AREA AL STAGEA AREA. ASI TENDREMOS AL ARCHIVO LISTO PARA SER ENPAQUETADO. 
# * GIT COMMIT: NOS PERMITE CERARR EL PAQUETE CON EL CONJUNTO DE CAMBIOS, AS IPODEMOS PASARLO A UNA VERSION DE NUESTRO REPOSITORIO.
# * GIT LOG: ADMINISTRA TODOS LOS CAMBIOS EN EL REPOSITORIO



def print_hola():
    print ("hola")
    

#CON LA CREACION DEL MAIN. SE ESTA TRABAJANDO EN EL PRIMER ESTADO.
#ESTE ESTADO DETECTA QUE HAY CAMBIOS EN EL REPOSITORIO. 