# GIT: ES UN SISTEMA DE CONTROL DE VERSIONES GRATUITO Y DE CODIGO ABIERTO. 
# ES UN SISTEMA QUE NOS PERMITE TENER DIFERENTES VERSIONES DE NUESTRO PROYECTO, Y SI COMETEMOS UN ERROR EN ALGUN PUNTO, PODEMOS VOLVER A ESA INSTANCIA PARA
# ARREGLARLO. 
# TIENE TRES ESTADOS: 
# * WORKING AREA: AREA DONDE SE ESTA TRABAJANDO, ESCRIBIENDO EL CODIGO. PREPARAMOS LAS CAJAS 
# * STAGE AREA: SE AGREGAN LAS CAJAS LISTAS
# * REPOSITORY: YA ES EL LOTE LISTO

# REPOSITORIO: ES UN ESAPCIO CENTRALIZADO DONDDE SE ALMACENA, ORGANIZA, Y SE MNATIENE Y DIFUNDE INFO, ES LA CARPETA QUE CONTIENE NUESTRO PROYECTO PARA COMPARTIRLO 4
# CON NUESTRO EQUIPO, PARA DESPUES ALMACENARLO EN LA NUBE. 

# PARA CREAR UN REPOSITORIO, HAY QUE SEGUIR LOS SIGUIENTES PASOS: 
# * GIT INIT: CREA REPOSITORIO DE FORMA LOCAL, EN LA CARPETA POSICIONADA. Y TAMBIEN EN ALGUNA CARPETA DONDE NO ESTEMOS POSICIONADOS, PASANDOLE LA DIRECCION
# * GIT STATUS: 
# * GIT ADD:
# * GIT COMMIT: 
# * GIT LOG: 


def print_hola():
    print ("hola")
    